def forca(x=0):
    if x==0:
        print('  ----------')
        print('  | ')
        print('  | ')
        print('  | ')
        print('  | ')
        print('  | ')
        print('__|______ ')
        print('|       |___')
        print('|___________|')
    elif x==1:
        print('  ----------')
        print('  |      O')
        print('  | ')
        print('  | ')
        print('  | ')
        print('  | ')
        print('__|______ ')
        print('|       |___')
        print('|___________|')
    elif x==2:
        print('  ----------')
        print('  |      O')
        print('  |      |')
        print('  |      |')
        print('  | ')
        print('  | ')
        print('__|______ ')
        print('|       |___')
        print('|___________|')
    elif x==3:
        print('  ----------')
        print('  |      O')
        print('  |     \|')
        print('  |      |')
        print('  | ')
        print('  | ')
        print('__|______ ')
        print('|       |___')
        print('|___________|')
    elif x==4:
        print('  ----------')
        print('  |      O')
        print('  |     \|/')
        print('  |      |')
        print('  | ')
        print('  | ')
        print('__|______ ')
        print('|       |___')
        print('|___________|')
    elif x==5:
        print('  ----------')
        print('  |      O')
        print('  |     \|/')
        print('  |      |')
        print('  |     / ')
        print('  | ')
        print('__|______ ')
        print('|       |___')
        print('|___________|')
    elif x==6:
        print('  ----------')
        print('  |      O')
        print('  |     \|/')
        print('  |      |')
        print('  |     / \ ')
        print('  | ')
        print('__|______ ')
        print('|       |___')
        print('|___________|')